kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: rhel8.5-devops-tools
  namespace: test-vms
  labels:
    flavor.template.kubevirt.io/medium: 'true'
    os.template.kubevirt.io/fedora35: 'true'
    template.kubevirt.io/type: vm
    vm.kubevirt.io/template: fedora-server-medium
    vm.kubevirt.io/template.namespace: openshift
    workload.template.kubevirt.io/server: 'true'
  annotations:
    iconClass: icon-rhel
    name.os.template.kubevirt.io/rhel8.5: Red Hat Enterprise Linux 8.5 For DevOps
    template.kubevirt.io/provider: Red Hat 
    template.kubevirt.ui/parent-provider: Red Hat
    template.kubevirt.ui/parent-provider-url: 'https://www.fedoraproject.org'
    template.kubevirt.ui/parent-support-level: Full 
objects:
  - apiVersion: kubevirt.io/v1
    kind: VirtualMachine
    metadata:
      annotations:
        vm.kubevirt.io/validations: |
          [
            {
              "name": "minimal-required-memory",
              "path": "jsonpath::.spec.domain.resources.requests.memory",
              "rule": "integer",
              "message": "This VM requires more memory.",
              "min": 1073741824
            }
          ]
      labels:
        app: '${NAME}'
        vm.kubevirt.io/template: rhel8-server-medium
        vm.kubevirt.io/template.revision: '1'
        vm.kubevirt.io/template.version: v0.19.4
      name: '${NAME}'
    spec:
      dataVolumeTemplates:
        - metadata:
            name: '${NAME}-rootdisk'
          spec:
            storage:
              resources:
                requests:
                  storage: 20Gi
              accessModes: []
              storageClassName: ocs-external-storagecluster-ceph-rbd
            source:
              pvc:
                name: rhel8.5-devops-tools
                namespace: test-vms
      running: false
      template:
        metadata:
          annotations:
            vm.kubevirt.io/flavor: medium
            vm.kubevirt.io/os: rhel8
            vm.kubevirt.io/workload: server
          labels:
            kubevirt.io/domain: '${NAME}'
            kubevirt.io/size: medium
        spec:
          domain:
            cpu:
              cores: 1
              sockets: 1
              threads: 1
            devices:
              disks:
                - name: cloudinitdisk
                  disk:
                    bus: virtio
                - name: rootdisk
                  bootOrder: 1
                  disk:
                    bus: virtio
              interfaces:
                - name: nic-0
                  model: virtio
                  masquerade: {}
              networkInterfaceMultiqueue: true
              rng: {}
              gpus: []
              hostDevices: []
            machine:
              type: pc-q35-rhel8.4.0
            resources:
              requests:
                memory: 4Gi
          evictionStrategy: LiveMigrate
          networks:
            - name: nic-0
              pod: {}
          terminationGracePeriodSeconds: 180
          volumes:
            - name: cloudinitdisk
              cloudInitNoCloud:
                userData: |
                  #cloud-config
            - name: rootdisk
              dataVolume:
                name: '${NAME}-rootdisk'
          hostname: '${NAME}'
parameters:
  - name: NAME
    description: Name for the new VM
    required: true
  - name: CLOUD_USER_PASSWORD
    description: Randomized password for the cloud-init user
    generate: expression
    from: '[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{4}'
